///New
export const REDUX_UPDATE_CURRENT_USER_ROLE = "REDUX_UPDATE_CURRENT_USER_ROLE";
export const REDUX_LOGOUT_CURRENT_USER = "REDUX_LOGOUT_CURRENT_USER";
export const REDUX_UPDATE_CURRENT_USER = "REDUX_UPDATE_CURRENT_USER";
export const REDUX_UPDATE_LOADING_STATE = "REDUX_UPDATE_LOADING_STATE";
export const REDUX_UPDATE_USER_DATA = "REDUX_UPDATE_USER_DATA";
export const REDUX_API_DOCUMENTATION = "REDUX_API_DOCUMENTATION";
